ci: introduce final check step

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -74,3 +74,25 @@ jobs:
         run: |
           cachix watch-exec bernardo -- \
           nix build -L .\#packages.x86_64-linux.${{ matrix.pkg }}
+
+  check:
+    runs-on: ubuntu-latest
+    needs: [ build ]
+    if: always()
+    steps:
+      - name: check
+        run: |
+          status_uri="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs"
+          user_str="admin:${{ secrets.PAT }}"
+          run="$(curl -X GET -s -u "${user_str}" "${status_uri}")"
+          jobs="$(jq '.jobs[]' <<< "${run}")"
+          statuses="$(jq '{job: .name, status: .conclusion}' <<< "${jobs}")"
+          builds="$(jq 'select(.job | contains("build"))' <<< "${statuses}")"
+          failed="$(jq 'select(.status | contains("success") | not)' <<< "${builds}")"
+
+          if [ -z "${failed}" ]; then
+            echo "OK"
+          else
+            echo "FAIL"
+            exit 1
+          fi
